#!/usr/bin/python
# -*- coding: gbk -*-


import urllib, urllib2, cookielib
import sys
import os
from getpass import getpass
try:
    from bs4 import BeautifulSoup
except:
    print "Error,this may help:"
    print "    pip install BeautifulSoup4"
try:
    import requests
except:
    print "Error,this may help:"
    print "    pip install requests"

try:
    sys_encode = os.popen('locale').readlines()[0].split('.')[1].strip()[:-1]  #popen（）函数：打开命令中的文件，或者读取命令下的终端返回信息  popen（）里面的参数是终端命令
except:
    print "please make sure running this script on *nix system"
    sys.exit(0)
username = raw_input("ID: ")   #从键盘读取用户名，raw_input() 全部以字符串的形式读取
password = getpass("PASSWORD: ") #专门用于输入密码的模块，带的参数是提示字符串
comment = raw_input("COMMENT: ")
comment = comment.decode(sys_encode)  #对评价进行解码
degree = raw_input("degree(1-8,1 is the best): ")
degree = degree.decode(sys_encode).encode('GBK')
if int(degree)  not in range(1,8):
    print "input out of range,retry again"
    sys.exit(0)

degree_const = {  #等级对应分数的字典
        1: '0.99',
        2: '0.95',
        3: '0.9',
        4: '0.85',
        5: '0.8',
        6: '0.7',
        7: '0.6',
        8: '0.4'}
login_data = {       #注意，我们有的时候需要将字典json化
        'zjh': username.decode(sys_encode),
        'mm': password.decode(sys_encode),
        'type': 'sso'}
login = requests.post('http://10.3.240.70/jwLoginAction.do', data=login_data)  #进行登录，表单提交  就是一个简单的post，需要提交的表单参数，带在后面。
cook = "JSESSIONID=" + login.cookies['JSESSIONID']
fetch_list = requests.get('http://10.3.240.70/jxpgXsAction.do?oper=listWj',cookies=login.cookies)
soup = BeautifulSoup(fetch_list.content.decode('gbk'))   #不用xpath的话，得到的响应直接放在bs里面
data_init = soup.find_all(title="评估")
data = []
for i in data_init:
    data.append({'wjbm':i['name'].split('#@')[0],
        'bpr':i['name'].split('#@')[1],
        'pgnr':i['name'].split('#@')[5],
        'wjmc':i['name'].split('#@')[3],
        'bprm':i['name'].split('#@')[2],
        'pgnrm':i['name'].split('#@')[4],})
if len(data) == 0:
    print "login error OR you have already done"
    sys.exit(0)   #python程序退出

for i in data:
    pre_post_data = {
        'wjbm': i['wjbm'].encode('GBK'),
        'bpr': i['bpr'].encode('GBK'),
        'pgnr': i['pgnr'].encode('GBK'),
        'oper': 'wjShow',
        'wjmc': i['wjmc'].encode('GBK'),
        'bprm': i['bprm'].encode('GBK'),
        'pgnrm': i['pgnrm'].encode('GBK'),
        'pageSize': '20',
        'page': '1',
        'currentPage': '1',
        'pageNo':''}
    headers = {
            'Host': '10.3.240.70',
            'Referer': 'http://10.3.240.70/jxpgXsAction.do?oper=listWj',
            }
    fake_click = requests.post('http://10.3.240.70/jxpgXsAction.do', data=pre_post_data, cookies=login.cookies, headers=headers) #有了
    post_data = {
        'wjbm':i['wjbm'].encode('GBK'),
        'bpr':i['bpr'].encode('GBK'),
        'pgnr':i['pgnr'].encode('GBK'),
        '0000000021':'10_'+degree_const[int(degree)],
        '0000000022':'10_'+degree_const[int(degree)],
        '0000000023':'5_'+degree_const[int(degree)],
        '0000000024':'20_'+degree_const[int(degree)],
        '0000000025':'10_'+degree_const[int(degree)],
        '0000000026':'5_'+degree_const[int(degree)],
        '0000000027':'5_'+degree_const[int(degree)],
        '0000000028':'20_'+degree_const[int(degree)],
        '0000000029':'10_'+degree_const[int(degree)],
        '0000000030':'5_'+degree_const[int(degree)],
        'zgpj': comment.encode('GBK')
    }
    headers = {
            'Host': '10.3.240.70',
            'Referer': 'http://10.3.240.70'
            }   #这个响应头感觉好鸡肋

    #最重要的一步
    vote = requests.post('http://10.3.240.70/jxpgXsAction.do?oper=wjpg', data=post_data, cookies=login.cookies, headers=headers)  #最后，其实就是使用post进行这样一个表单提交，提交表单的方式，基本都是post
    out =  vote.content     #与vote.text  效果一样，得到响应网页的源码        #需要post的数据，就是我们需要提交的数据 data = post_data
    if str(out).find('成功') >= 0:
        print "---- success on " + i['bprm']
    else:
        print "---- fail on " + i['bprm']
        print "so embarrassed.."

print "Done,see you"
